### ISSUE TITLE
Rolling errors

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#9] opened 2021-05-01 02:02 UTC
![image](https://user-images.githubusercontent.com/82736191/116767593-8b178700-aa07-11eb-86d5-5f981c2e9c90.png)

When starting Mudae AutoBot Limited.py, if there is no scroll, it displays this error.
I also modified it here to roll faster, because it was extremely robotic and this error occurred.
Would it be possible for the bot to start running again without having to restart?

![image](https://user-images.githubusercontent.com/82736191/116767651-e0539880-aa07-11eb-9ab7-65dd9f392ab6.png)

I tried to use SoulmateKakSnipeOnly with soulemoji_list, without success, they are ignored

**Comment by vivinano** [comment] 2021-05-01 03:24
Don’t know what you mean by no scroll but basically how rolling works is that it timeout purposely to stop spamming a channel so if it never receives a timer this is so the rolling method is handled dynamically Instead of statically. And the reason that it’s must be restarted as this is a coroutine that is created upon ready so it can be created and left to do its task in the background 

One way might be adding a on message listener to check for a discord message that says reset but that might not work or might cause issues 

Again as I don’t have soulmates I can’t really test the code any changes you made I cannot confirm if it works. I can tell you that the current implementation ignores soulmates that don’t have $EC set so if you didn’t set your soulmates to a different EC color it will ignore

**Comment by vivinano** [comment] 2021-05-01 03:34
wheter its fast or slow is a personal preference I play on mobile sometimes and I have to manually type $w and that takes varies from a few secs to really fast.  to say that it rolling to slow or to fast makes it robotic doesnt really make sense to a normal player you are simply typing $wg and it takes you a few seconds. 

as since you know its a bot makes you think that it is robotic as this is only a single-blind test you knowing that you are using a bot makes it feel like a bot but to normal users they are not exactly timing your bot rolls to see if your a bot. 

> ![image](https://user-images.githubusercontent.com/33008397/116769703-10049f80-aa0c-11eb-94d1-f029c8be626c.png)`

make sure your soulmates pass this check or else it will be ignored.

> ![image](https://user-images.githubusercontent.com/33008397/116769714-388c9980-aa0c-11eb-9b70-7c982d5b406f.png)

and this code is what makes the coroutine. do with this knowledge what you will but simply restarting my program is a non-issue as I have to make changes every time I need to resolve an issue. you could maybe increase the timeout but do keep in mind that this might cause the bot to actually spam the channel until it receives the desired input needed to continue

**Comment by BellaDona007** [comment] 2021-05-01 04:20
> issues Again as I don’t have soulmates I can’t really test the code any changes you made I cannot confirm if it works. I can tell you that the current implementation ignores soulmates that don’t have $EC set so if you didn’t set your soulmates to a different EC color it will ignore
>

The only change I made on this new one was just to put the embedcolor that I want him to recognize as a soul mate

I will keep the original value in this part then and see if the problem occurs in the rolls

![image](https://user-images.githubusercontent.com/82736191/116770564-4b5a9a80-aa1b-11eb-8a55-d0359edd9066.png)

**Comment by vivinano** [comment] 2021-05-01 04:32
hope you know that right now its set to `not in` so it will check if the values is not the set color

**Comment by BellaDona007** [comment] 2021-05-01 05:41
Just configuring:
token
channel_id
claim_delay
kak_delay
"SoulmateKakSnipeOnly": "True"
SoulmateKakColorValue ":" # 0004ff "
And running MudaeAutoBot_Limitd.py, without having rolls, it presents an error and asks to restart (This didn't happen before)
It also sometimes happens that he is rolling around many times without even having a roll.
And again the characters with embedcolor are ignorant.
I don't know if there was a change in Mudae, but the old versions that I used one stopped taking the kakera from embedcolor and started to ignore the lack of kakerapower and always try to catch kakeras

**Comment by vivinano** [comment] 2021-05-01 10:03
As stated when I pushed code I was trying to phase out embed color 

So it’s set to snipe all $EC that is “NOT IN” default colors

As for rolling the “limited” version of the code was just a copy and paste of the original code with the changes made to limit servers 

Personally I wanted to avoid making the limited version as I requires more set up then the previous one but as requested I provided the same code but with more settings required to make it limited so it might be issues with variables not being set correctly or not being found that it requires for checks

**Comment by BellaDona007** [comment] 2021-05-01 18:37
I used the normal version I made the changes you indicated once, to see if it was not a problem at MudaeAutoBot_Limitd.py
change` if message.author.id == mudae: `>>> `if message.author.id == mudae and message.channel.id in [111111,22222]:`
change` if user.id == mudae: `>>>` if user.id == mudae and reaction.message.channel.id in [111111,222222]:`

It turns out that he is ignoring the lack of kakerapower and is not identifying the "namelist"

I gave up trying to get kakera with embedcolor, because even in the old version it stopped working, without me making any changes

**Comment by BellaDona007** [comment] 2021-05-01 22:34
This part is not working, would it be due to the bot this language PT-BR?

![image](https://user-images.githubusercontent.com/82736191/116796586-fa4ab500-aab3-11eb-87d2-32dec43c010b.png)

The original message is:
"You can't react to kakera for 10 min. ($ ku)"
The message in PT-BR
"Você não pode reagir a um kakera antes 10 min. ($ku)"

**Comment by vivinano** [comment] 2021-05-01 22:41
As long as the kakera starts with your username and has “kakera” in the message it will trigger

**Comment by BellaDona007** [comment] 2021-05-01 22:42
I don't know what happened, but there are 3 days that even the version I used before stopped trigger

**Comment by vivinano** [comment] 2021-05-02 00:17
Very vague I need more info. We were talking about multiple issues and broken is not defining enough 

If it's soulmate kakera sniping them I keep explaining that it has been changed on how it works that as long as you have set it to a non default color

**Comment by BellaDona007** [comment] 2021-05-02 01:09
During the roll:
1- If you start the program with no roll available, the program displays the image

![image](https://user-images.githubusercontent.com/82736191/116767593-8b178700-aa07-11eb-86d5-5f981c2e9c90.png)

2 - It does not react to the waifus corresponding to the embedcolor defined in SoulmateKakColorValue

3 - He does not identify the kakera cooldown, in my roll or outside of it

**Comment by vivinano** [comment] 2021-05-02 02:22
1. if you have no roll avaible it awaits a message that says **username** , xxxxx xxxx xxxx 60 mins left unless your server has a different. if you get a different result then below \/ then let me know but looking at the response it can still parse this correctly 

> ![image](https://user-images.githubusercontent.com/33008397/116799930-8cf64e80-aaca-11eb-990e-e81271df3ba9.png)


2. I changed the check to so as of now SoulkakColorValue is not used and is now using anything that isnt "Default Value". this was a change so it required less set up for users and didnt limit players to only use 1 color.

>  ![image](https://user-images.githubusercontent.com/33008397/116799967-f1191280-aaca-11eb-8e0b-6c6c52762400.png)


3. Timer for kakera rolls only effect the "not Soulmate kakera" and "KakeraP" gets its own reaction sniping because kakeraP is free so it will make the attempt to avoid missing KakeraP 

KakeraP
> ![image](https://user-images.githubusercontent.com/33008397/116800054-946a2780-aacb-11eb-970a-ac8e81787681.png)

Soulmate Kakera
> ![image](https://user-images.githubusercontent.com/33008397/116800059-a350da00-aacb-11eb-85c0-a1442d5fc04f.png)

Not Soulmate "Normal Kakera"
> ![image](https://user-images.githubusercontent.com/33008397/116800070-b663aa00-aacb-11eb-8c3e-965957994985.png)

**Comment by vivinano** [comment] 2021-05-02 19:57
https://github.com/discord/discord-api-docs/blob/master/docs/Change_Log.md#DOCS_TOPICS_THREADS

there is a discord api changes itself which is why there are errors 

>  ![image](https://user-images.githubusercontent.com/33008397/116825847-0dff2580-ab5f-11eb-8a1f-ee5d49da2116.png)

so this means there will be certain bugs and errors that are out of my control

**Comment by BellaDona007** [comment] 2021-05-02 21:00
> https://github.com/discord/discord-api-docs/blob/master/docs/Change_Log.md#DOCS_TOPICS_THREADS
> 
> there is a discord api changes itself which is why there are errors
> 
> > ![image](https://user-images.githubusercontent.com/33008397/116825847-0dff2580-ab5f-11eb-8a1f-ee5d49da2116.png)
> 
> so this means there will be certain bugs and errors that are out of my control

Right after that date here kakera cooldown, SoulmateKakColorValue and namelist stopped working

**Comment by vivinano** [comment] 2021-05-03 05:40
yeah alright im gonna close this issue and the other issue and make a umbrella issue so that way the issue isnt spread across issues

**Closed by vivinano** 2021-05-03 05:40 UTC
