### ISSUE TITLE
Setup Help?

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#10] opened 2021-05-02 05:55 UTC
Hey I'm not really familiar with programming but I followed all the instructions in the readme. The bot has no issue sniping kakera but it seems to not be recognizing any of the characters I've put in the namelist. In addition to that, I set my min_kak value to 400 but I've seen the bot completely ignore several of 400+ kakera characters. Is there something I can do to fix this issue?

**Comment by RecentYogurt** [comment] 2021-05-02 05:59
I'd also like to ask how the timing on the rolls work because when I ran the program it just kept spamming the command even when I didn't have rolls left so I just decided to manually roll and set rolling and pokemon rolling to false. So far I'm using the program to snipe kakera but I'm having trouble setting it up to snipe characters.

**Comment by seriaati** [comment] 2021-05-02 06:33
yeah same so far im only using it to snipe kakera

**Comment by vivinano** [comment] 2021-05-02 15:48
namelist has to be a "Exact" match spaces and all of that
series list is more forgiving and will match partials 

when you say spam. how many times is it spamming the server currently cause it suppose to time out or when it gets the your out of rolls command. 

so exmaple you roll $wg it will roll until u get the "Username" and min left (message) it either gets that message or it times out and stops the automated roll itself to prevent spam 

Pokemon slots tho it works a little different since there is a delay with pokeslot the whole animation thing it post $p (3) times when optimally its suppose to be (2) times 
one time for a successful roll and the 2nd to get the cooldown timer

If you can post the setting_json image so I can review if the settings are correct. feel free to blur out the channel ids 
but please do not post ur token. Also let me know if ur using the limited version as that requires a little more set up.

after which if it still doesnt work I can walk thru some debugging code to insert in help determine what is going on

**Comment by FatPain** [comment] 2021-05-02 17:51
Hi, I was also having the claiming issue, I'm only trying to use the limited bot to claim and snipe kakera.  I'm not sure if I messed up the settings somewhere.
![image](https://user-images.githubusercontent.com/25698507/116822478-91f7e400-ab44-11eb-8cfc-332763d303f4.png)

**Comment by FatPain** [comment] 2021-05-02 18:06
I'm not sure why but when rolling, message.embeds = [ ], so the entire claiming section of the code is skipped

**Comment by vivinano** [comment] 2021-05-02 18:12
That is interesting where are you printing message.embeds ? And if your server set in a way that it doesn't use embeds ??

**Comment by vivinano** [comment] 2021-05-02 18:19
> ![image](https://user-images.githubusercontent.com/33008397/116823184-118bb000-ab51-11eb-8c0b-6fc4bf6ec14d.png)

right here print message.embeds and it still empty ?

**Comment by RecentYogurt** [comment] 2021-05-02 18:19
![settingsjson](https://user-images.githubusercontent.com/83528449/116823111-8a7e0e00-ab37-11eb-95c8-60de5ab297be.png)
This is what I have in settings.json. About the spamming rolls, the program would roll $wa and $p even after the message saying I don't have rolls and it seemed like it wouldn't stopped so I just shut the program off.  I'll also post an image of what the characters look like when they get rolled on my discord server. 
![mudae example](https://user-images.githubusercontent.com/83528449/116823241-345d9a80-ab38-11eb-9e5c-f46db5866729.png)

**Comment by vivinano** [comment] 2021-05-02 18:23
about rolls the rolls basically go until it get message and should timeout otherwise. even tho i havent tested out the limited_Version

its a copy and paste with the code to limit the servers it monitors in

try the rolls and have faith it will stop on a different server and tell me if i need to modify the code 


and can you also print message.embeds on line  

> ![image](https://user-images.githubusercontent.com/33008397/116823346-fbcaba80-ab51-11eb-82c3-8e6ac72dd407.png)

**Comment by FatPain** [comment] 2021-05-02 18:44
> That is interesting where are you printing message.embeds ? And if your server set in a way that it doesn't use embeds ??

I'm printing right before it checks empty embed. My server does use embeds so I'm not too sure what the issue is
![image](https://user-images.githubusercontent.com/25698507/116823778-1e59d500-ab4c-11eb-86c4-4a13faa4886f.png)

**Comment by vivinano** [comment] 2021-05-02 18:47
right here what is your multichannel ids

> ![image](https://user-images.githubusercontent.com/33008397/116823892-24a07f00-ab55-11eb-8eaf-eea1d734405d.png)


> ![image](https://user-images.githubusercontent.com/33008397/116823917-4994f200-ab55-11eb-8bed-67da02fddbb4.png)

**Comment by FatPain** [comment] 2021-05-02 18:49
my multichannel and channel_id is the the same, as I'm only using the bot on one server

**Comment by RecentYogurt** [comment] 2021-05-02 19:07
When I set it to print and Everytime mudae rolls a character it prints an empty line it seems

**Comment by RecentYogurt** [comment] 2021-05-02 19:08
I've been using the limited version as I only use it for one server so my multiID is the same as the server ID

**Comment by vivinano** [comment] 2021-05-02 19:09
okay i feel like some changes were made with the discord api or something cause it was working yesterday and now testing it the results are different give me a few 
cause now it not stopping when rolling and getting blank values like you guys are stating

**Comment by vivinano** [comment] 2021-05-02 19:23
I think there is something wrong with the on_message listener cause even trying to print message.content which should spam me with all the random jargon is no longer spamming with random jarghon

**Comment by vivinano** [comment] 2021-05-02 19:56
> ![image](https://user-images.githubusercontent.com/33008397/116825773-ab0d8e80-ab5e-11eb-928b-06f67701e6a8.png)
 so apprently the new discord api has removed the api for messages so until discord.py is updated it will not be able to get messages
@RecentYogurt @seriaati @FatPain 

https://github.com/discord/discord-api-docs/blob/master/docs/Change_Log.md#DOCS_TOPICS_THREADS

**Comment by RecentYogurt** [comment] 2021-05-02 20:07
do you think they'll reinstate the API for messages?

**Comment by vivinano** [comment] 2021-05-02 20:19
It gonna be on the maker of Discord.py since it is the wrapper for discord API I assume it will in the future but as an ETA im unsure.
But yeah i found it weird that it was working fine yesterday and today 3 users came to me with similar issues 

If i can find a guide on changing the code to work with new API 

Ill be leaving this issue open until it is fixed

but as of now both Sniping and rolling as they rely on messages are not working and only kakera sniping works since it is reaction based

**Comment by vivinano** [comment] 2021-05-03 05:41
yeah alright im gonna close this issue and the other issue and make a umbrella issue so that way the issue isnt spread across issues

**Closed by vivinano** 2021-05-03 05:41 UTC
