### ISSUE TITLE
help with slash rolling

### ISSUE THREAD

**Issue by CriticalMomento** [vivinano/MudaeAutoBot#201] opened 2022-08-26 16:17 UTC
will it claim if reaction is like this?
![image](https://user-images.githubusercontent.com/74601249/186948793-ab3efe83-97d2-41ca-a5aa-014c5357c4df.png)

**Comment by CriticalMomento** [comment] 2022-08-26 16:19
also how do i get slash id and slash guild id?

**Comment by CriticalMomento** [comment] 2022-08-27 15:28
ok confirmed that it doesnt
so can i request you to make i so it claims button hearts?
🥺

**Comment by vivinano** [comment] 2022-08-27 23:42
It claims buttons on claim just not on kakera also you to set up slash rolling options like slash id and slash guild for button snipes

**Comment by CriticalMomento** [comment] 2022-08-28 02:55
> It claims buttons on claim just not on kakera also you have to set up slash rolling options like slash id and slash guild for button snipes
> […](#)
> Sent from my iPhone
> On Aug 27, 2022, at 11:28 AM, CriticalMomento ***@***.***> wrote: ﻿ ok confirmed that it doesnt so can i request you to make i so it claims button hearts? 🥺 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

like this?
![image](https://user-images.githubusercontent.com/74601249/187055430-4d0ea171-233f-44c8-8541-f7bbc0bb1ddb.png)

**Comment by CriticalMomento** [comment] 2022-08-28 03:14
hmm i get this error 
![image](https://user-images.githubusercontent.com/74601249/187055830-7e3031a1-755d-4edb-924e-ac6f0eb038bb.png)

**Comment by vivinano** [comment] 2022-08-28 04:39
No set prefix back to normal also make sure you have the new version of the repo some changes were made

**Comment by CriticalMomento** [comment] 2022-08-28 05:47
> No set prefix back to normal also make sure you have the new version of the repo some changes were made

i set the prefix back to normal which is "$".
downloaded your latest repo which is mudae main
![image](https://user-images.githubusercontent.com/74601249/187059636-1a989f37-5ed0-43ab-94ad-73c6c386b78c.png)
still get this

**Comment by CriticalMomento** [comment] 2022-08-28 05:55
i checked some closed tickets and saw 1 guy managed to solve it by installing discum through git
i tried it but 
![image](https://user-images.githubusercontent.com/74601249/187059867-5d140221-070b-41c6-8561-f73226e83f11.png)

**Comment by vivinano** [comment] 2022-08-28 06:33
Slashget wasn’t getting assigned properly though discum as you see that I made a pull request with changes on the latest discum repo to fix it so I made 2 code variations I think of slashget for the code prefix and after the fix so try to print out the slashget variable and see if it is empty

**Comment by CriticalMomento** [comment] 2022-08-28 08:18
> Slashget wasn’t getting assigned properly though discum as you see that I made a pull request with changes on the latest discum repo to fix it so I made 2 code variations I think of slashget for the code prefix and after the fix so try to print out the slashget variable and see if it is empty
> […](#)
> Sent from my iPhone
> On Aug 28, 2022, at 1:55 AM, CriticalMomento ***@***.***> wrote: ﻿ i checked some closed tickets and saw 1 guy managed to solve it by installing discum through git i tried it but — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

soo i just have to wait for now?

**Comment by vivinano** [comment] 2022-08-28 15:41
No It still works with button claiming just need configuration

**Comment by CriticalMomento** [comment] 2022-08-29 10:26
> No It still works with button claiming just need configuration
> […](#)
> Sent from my iPhone
> On Aug 28, 2022, at 4:18 AM, CriticalMomento ***@***.***> wrote: ﻿ Slashget wasn’t getting assigned properly though discum as you see that I made a pull request with changes on the latest discum repo to fix it so I made 2 code variations I think of slashget for the code prefix and after the fix so try to print out the slashget variable and see if it is empty … Sent from my iPhone On Aug 28, 2022, at 1:55 AM, CriticalMomento @.***> wrote: ﻿ i checked some closed tickets and saw 1 guy managed to solve it by installing discum through git i tried it but — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. soo i just have to wait for now? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

and what are those config that i need to do?

**Comment by CriticalMomento** [comment] 2022-08-29 13:28
![image](https://user-images.githubusercontent.com/74601249/187212213-e889bb5b-b60c-4249-a037-29d963e8b9f8.png)
welll.....it logs ppl rolling stuff but not doing the rolls or claiming

**Comment by CriticalMomento** [comment] 2022-08-31 07:12
i tried everything
still getting same erros
might just give using main and cope with v4

**Comment by vivinano** [comment] 2022-08-31 13:55
You won't have button support I don't think 🤔 I'll try when I get home with my personal and see if there is an issue I need to fix

**Comment by CriticalMomento** [comment] 2022-08-31 14:24
> You won't have button support I don't think 🤔 I'll try when I get home with my personal and see if there is an issue I need to fix

🙏 🙏 🙏 🙏 🙏

**Comment by CriticalMomento** [comment] 2022-08-31 16:07
@vivinano 
![image](https://user-images.githubusercontent.com/74601249/187726225-b02b0dd5-bacb-46ad-8660-f6df548b6781.png)
do i need to install this
i havent touched it

**Comment by vivinano** [comment] 2022-08-31 16:22
![image](https://user-images.githubusercontent.com/33008397/187729192-08e9ca39-3b92-4ea1-a0ef-82f65cdea73a.png)


still works so nothing is wrong

**Comment by CriticalMomento** [comment] 2022-08-31 17:00
> ![image](https://user-images.githubusercontent.com/33008397/187729192-08e9ca39-3b92-4ea1-a0ef-82f65cdea73a.png)
> 
> still works for me So unsure what is going on on your end atleast
![Code_wKLLv0FYTi](https://user-images.githubusercontent.com/74601249/187736790-23f97d9a-a9db-49bc-af09-ffad33033cad.png)
i configered it like that
guild slash is is basically server id right?
and slash id is basically channel id correct?

**Comment by vivinano** [comment] 2022-08-31 17:13
uh could you name it better ? all these short hand terms are confusing me.

**Comment by CriticalMomento** [comment] 2022-08-31 17:56
> uh could you name it better ? all these short hand terms are confusing me.

basically what i named channel 1 different server (1) is but a channel of a server 1
and channel 1 different server (2 ) is a channel of server 2

**Comment by vivinano** [comment] 2022-08-31 18:26
as long as it the same match and the 1st server has slash commands enabled

**Comment by CriticalMomento** [comment] 2022-09-01 01:36
> as long as it the same match and the 1st server has slash commands enabled

yea it has slash enabled i think they do match
i cant see any errors in my settings files so i dont even know if i am doing anything wrong

**Comment by CriticalMomento** [comment] 2022-09-01 01:52
let get this correct then
slash id = channel id
slash guild id = server id of the server in which the channel resides in
right?

**Comment by vivinano** [comment] 2022-09-01 02:25
Yes I think that what it is

**Comment by CriticalMomento** [comment] 2022-09-01 02:26
> Yes I think that what it is
> […](#)
> Sent from my iPhone
> On Aug 31, 2022, at 9:53 PM, CriticalMomento ***@***.***> wrote: ﻿ let get this correct then slash id = channel id slash guild id = server id of the server in which the channel resides in right? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

yep idk what the problem is then

**Comment by CriticalMomento** [comment] 2022-09-01 02:30
![image](https://user-images.githubusercontent.com/74601249/187819329-e9f12067-b358-4a4b-9412-e39034c99582.png)
well the error says it has something do with this  ( your code ^ )
![image](https://user-images.githubusercontent.com/74601249/187819449-5f3507f4-f89b-4963-a3b2-84f2aeda55db.png)
gateway ^
![image](https://user-images.githubusercontent.com/74601249/187819488-3d65ed03-65b9-401b-8bf2-9b234789706b.png)
error ^

**Comment by vivinano** [comment] 2022-09-01 08:31
![image](https://user-images.githubusercontent.com/33008397/187868849-bd5f26f1-1b4e-4f30-9d34-b8be14deb507.png)

only way you will get unbound error is that your servers do not have the slash commands enabled hence it has nothing to query and pull data from

![image](https://user-images.githubusercontent.com/33008397/187869295-9cc9302c-8815-4931-982c-266cf3e2efeb.png)

and all sniping including button presses for claims are here

**Comment by CriticalMomento** [comment] 2022-09-01 08:49
> ![image](https://user-images.githubusercontent.com/33008397/187868849-bd5f26f1-1b4e-4f30-9d34-b8be14deb507.png)
> 
> only way you will get unbound error is that your servers do not have the slash commands enabled hence it has nothing to query and pull data from
> 
> the original way for getting "slashget" was commented out due to discum error but it was recently fixed so you could go back for the originally method instead of my workaround
> 
> ![image](https://user-images.githubusercontent.com/33008397/187869295-9cc9302c-8815-4931-982c-266cf3e2efeb.png)
> 
> and all sniping including button presses for claims are here

however slash cmds are enabled....
![image](https://user-images.githubusercontent.com/74601249/187873201-e0eaf632-5edd-445b-beef-63af518c35f2.png)

**Comment by CriticalMomento** [comment] 2022-09-01 09:05
@vivinano by previous workaround you mean this?
![image](https://user-images.githubusercontent.com/74601249/187876515-a2fbd2ae-03ca-4088-9214-3ce577ad22dd.png)

**Comment by CriticalMomento** [comment] 2022-09-01 16:25
> originally it was only s.get(wa) for example but due to the library only bringing back the 1st entry nothing happened so I had to change my code to go thru each entry manually after my pull request was approved you could go back to the way with s.get() or use the work around with the for loop

uhhh um i dont know python so i am totally lost on what to do

**Comment by vivinano** [comment] 2022-09-01 18:18
Which are you trying to roll Wg , hg ?

**Comment by CriticalMomento** [comment] 2022-09-02 10:17
> Which are you trying to roll Wg , hg ?

wg

**Comment by vivinano** [comment] 2022-09-02 16:48
And when you type in /wg you get a whole list of option right ?

**Comment by CriticalMomento** [comment] 2022-09-03 10:37
> And when you type in /wg you get a whole list of option right ?
> […](#)
> Sent from my iPhone
> On Sep 2, 2022, at 6:17 AM, CriticalMomento ***@***.***> wrote: ﻿ Which are you trying to roll Wg , hg ? wg — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

![image](https://user-images.githubusercontent.com/74601249/188266731-e9c48019-cb7e-4676-a1d2-f191f89926c1.png)
yes

**Comment by vivinano** [comment] 2022-09-03 17:55
At this point you might have to trouble shoot the issue at the code level specifically what is being slashget being set do and if it's not then trying to let me know what the issue is or trying to fix it yourself

**Comment by CriticalMomento** [comment] 2022-09-04 02:15
aaa sounds like something which i can't do...
oh well i will still notify you if i get it working or get another error

**Comment by CriticalMomento** [comment] 2022-09-08 16:29
@vivinano btw i see ppl reacting on kakera faster than me
i saw some previous threads which said to remove the .5 wait in mudae.py code and i did that
and yet ppl still do it faster than me
i have it on 0 btw

**Comment by vivinano** [comment] 2022-09-08 16:33
Depends is the kakera on button sniping also ?

**Comment by CriticalMomento** [comment] 2022-09-10 10:15
> Depends is the kakera on button sniping also ?
> […](#)
> Sent from my iPhone
> On Sep 8, 2022, at 12:29 PM, CriticalMomento ***@***.***> wrote: ﻿ @vivinano btw i see ppl reacting on kakera faster than me i saw some previous threads which said to remove the .5 wait in mudae.py code and i did that and yet ppl still do it faster than me i have it on 0 btw — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

nah its emoji reacting like this 
![image](https://user-images.githubusercontent.com/74601249/189478865-00cc6523-c5b0-49c9-966a-ce69865f2571.png)

**Comment by HentaiRyuu** [comment] 2022-09-13 10:28
> ![image](https://user-images.githubusercontent.com/33008397/187868849-bd5f26f1-1b4e-4f30-9d34-b8be14deb507.png)
> 
> only way you will get unbound error is that your servers do not have the slash commands enabled hence it has nothing to query and pull data from
> 
> the original way for getting "slashget" was commented out due to discum error but it was recently fixed so you could go back for the originally method instead of my workaround
> 
> ![image](https://user-images.githubusercontent.com/33008397/187869295-9cc9302c-8815-4931-982c-266cf3e2efeb.png)
> 
> and all sniping including button presses for claims are here

if i use `slashget = s.get([roll_prefix])`, i get this error
![image](https://user-images.githubusercontent.com/26791163/189872151-e58bba1d-bb98-4174-81d8-f7cf930089f3.png)


if i use
```
for sli in range(len(s.commands.get("options"))):
    if s.commands.get("options")[sli].get("name") == roll_prefix:
        slashget = s.commands.get("options")[sli]
```
this happen because nothing is assign to `slashget`
![image](https://user-images.githubusercontent.com/26791163/189872266-f371f52b-8c82-45f0-b62d-8aeff7bfc6b1.png)

ps. i updated discum to 1.4.1 (lasted one)

i think i know problem now, it because `slashCmds = resp.parsed.auto()['application_commands']` only get first 100 slash cmd.
so if my server have other bot (many bots) it will break.
then what should i do to get more than first 100 slash cmd?

**Comment by vivinano** [comment] 2022-09-13 17:10
You could see if application commands takes another param and limit the search parse

**Comment by vivinano** [comment] 2022-10-11 07:47
They are the slash variables as it’s a whole discord interaction instead of just doing a reaction 
But you don’t have to set slash rolling to true but the variables must be set

**Comment by vivinano** [comment] 2022-10-11 08:25
Slash rolling doesn’t have the be enabled but also it could be uh the discum needed to be updated 

I put a pull request that was recently accepted by the discum dev so you will have to update that gateway.py

**Closed** 2022-11-23 14:28 UTC
