### ISSUE TITLE
Running multiple bots on own server

### ISSUE THREAD

**Issue by Bronerman** [vivinano/MudaeAutoBot#76] opened 2021-07-15 15:27 UTC
First off, thanks for sharing the code for this bot, I really appreciate it. I looked though the closed questions and I did not seem to find a topic related to this. 
Currently, I'm running 3 bots on my own server. It works as expected when running 1 bot, but issues seem to arise when I run 3 at the same time. Usually there will be rolls left over on the unleveled bots (1/2 rolls) which I assume is due to the bots all entering commands at the same time. I've also noticed that claims do not act consistently. Occasionally, 1 or 2 bots will notice a waifu meeting minimum criteria or series list, while another will not (does not print out in the command or attempt to claim). I have tried different claim delays, but I believe the issue is that sometimes a bot does not pick up on the claim due to the simultaneous commands of the other bots. Any ideas on a way to fix or possibly stagger the bots?

One last issue that I cannot figure out is getting last claim min to consistently act as I want it to. My exact minute of reset is 00. I would like for last claim min to trigger in the last hour before the reset, but I have had it trigger in the 2nd hour, last hour, or not at all while experimenting with different values. Thanks. 

![Snag_25462d3d](https://user-images.githubusercontent.com/87488178/125814406-c4884eec-e533-432c-8990-2722f95669f4.png)

**Comment by vivinano** [comment] 2021-07-15 16:09
For claims there is a failsafe so if one bot was able to grab “X” then the other bots will ignore it because it sees that it is claimed already and will not make an attempt this check happen after the wait timer so I believe this is intended behavior

For rolls there a check that can be turned off to get more rolls it was a failsafe check to stop over Rolling so you could take disable that check and it will roll until I get the “no more message” also it’s set up to roll at reset so theoretically you could add a random wait() variable so that it will choose a random value of minute to roll I was gonna implement this but I feel like users would get impatient and make a issue about it not running correctly if it was random  

With the last min claim it the newest feature I added so it understandable that there might be a few bugs that need to be ironed out 
So as of now the last min snipe only works for “kakera value” and that kakera value calculation is not accurate 100% it’s using a modified formula that I found on the internet which does not take in account of keys owned or overall character owned 

Also ensure that the bot is getting the correct $settings because the bots could be using its default settings if it can’t read the file made 

Also last min sniping still has the failsafe to not claim claimed characters so if one bot succedds the other will ignore it and not snipe it keep it mind it has to successfully claim so they all attempt but you will only see one add the react 

So another thing is that how last min work is that it checks the time during a roll so if you want last hour then you do something like 59 as the mins and then do like 10 for last_min_kak and just to see if it working as intended but basically something has to be rolled during the last min claim window or else nothing is detected

**Comment by vivinano** [comment] 2021-07-16 02:36
any questions or concerns ???

**Comment by Bronerman** [comment] 2021-07-16 03:33
Thanks for the quick response. 
I understand the reasoning behind the behaviour of a bot claiming and another not printing out. I guess my understanding that all 3 bots (assuming they all have the same minimum kak requirement) would print out a notification that a claim was available and then one would successfully claim. I guess there must be some delay in mudae and that one will make a successful claim, another might notice before the claim, and the other might ignore it (failsafe). 

Thanks for pointing me towards the roll check, This would be the section of code correct?
            if varwait != None and varwait['content'].startswith(f"**{bot.gateway.session.user['username']}") and "$ku" not in varwait['content']:
                # We over-rolled.
                waifuwait = True
                if c_settings['rolls'] > 2 and not warned_overroll:
                    # We overrolled when we shouldn't have. Warn the user they can prevent this
                    warned_overroll = True
                    logger.warning("Please enable $rollsleft 0 feature to prevent overrolling")

Would I set this to false to disable the check?

I did notice the code for getting the correct $settings and I'll double check to make sure that's correct. 
I haven't noticed too many errors of last min sniping making a mistake on min kak last min, as long as the window is open (which I found inconsistent). 
I did test 58, 59, 60, 61. I guess I was looking for the print out "last min claim was attempted" to occur consistently in the last hour if a claim was available. However I set my min kak last min to 55 and I guess it might be probable that none of the rolls are above that value. I will try lowering as you suggested.

**Comment by vivinano** [comment] 2021-07-16 05:19
no if something is ignored it will not print that is is attempting to claim it will just go on like normal I mean i could add more prints but it just fills up the console to much if I add multi prints 

overall yeah u can turn warned_overroll to false and threotically it will no longer check for 2 rolls left and rolls until it hits the no rolls left 

No same as the top I try not to spam the channel consistantly with notifications so its not always a good indication of working just have the bot running on a very low kak to confirm a snipe happened cause for example b4 any roll in the last min claim window produced a last window claim avaible which just spammed the channel with 10x Number of last minute users
which was annoying so ive moved the notification in when it snipes to avoid 100+ prints of claim window available

**Comment by Bronerman** [comment] 2021-07-16 14:15
That makes sense that there would be too much spam. I have been relying a lot on the notifications to see if it is functioning correctly. 
I tested out the settings last night. 
I set warned_overroll to false and it did not solve the rolling to completion issue. 
With last_claim_min set to 59 and min_kak_last_min to 10, the bots still did not attempt a claim in the last hour before reset.

**Comment by Bronerman** [comment] 2021-07-16 14:18
I also forgot that I've infrequently had an issue with a bot not rolling at the start of the claim window. I did read in the previous closed issues that this might be related to a previous issue. Resetting the command prompt solves the issue.

**Comment by vivinano** [comment] 2021-07-16 14:24
alright well im gonna try to focus on the last min claim window issue right now 

so with the last min claim window does your server have kakera value set up or like or rank value ? like does it look like 

![image](https://user-images.githubusercontent.com/33008397/125963000-fb81b816-f307-4b7b-a210-2f4ccbe5329a.png)

or does it look different ?

**Comment by Bronerman** [comment] 2021-07-16 15:06
The output is slightly different, but I do believe it has all three enabled. 
![Snag_2a5975e1](https://user-images.githubusercontent.com/87488178/125968824-713461bb-73d4-4141-9547-0b27b0456939.png)

**Comment by vivinano** [comment] 2021-07-16 15:07
show me a roll cause that looks like a $im command

**Comment by Bronerman** [comment] 2021-07-16 15:09
Oh sorry about that.
![Snag_2a5c2fff](https://user-images.githubusercontent.com/87488178/125969202-bf377f2d-fd6f-4e75-a2bb-fb41bc07b3ae.png)

**Comment by vivinano** [comment] 2021-07-16 15:12
is_last_enable is set to True ?? correct ?

**Comment by Bronerman** [comment] 2021-07-16 15:15
![Snag_2a620dd4](https://user-images.githubusercontent.com/87488178/125970154-5212c9e1-c507-40ec-b689-2677511bec08.png)
Yes it is

**Comment by vivinano** [comment] 2021-07-16 15:16
in the setting.json i mean

**Comment by Bronerman** [comment] 2021-07-16 15:17
![Snag_2a63db03](https://user-images.githubusercontent.com/87488178/125970418-d3b5960f-a54c-4289-899d-555e70cc50a3.png)
Oh yes that is

**Comment by vivinano** [comment] 2021-07-16 15:19
so in your channeldata folder that should contain a txt file with your channelid make sure the data in there matches the $setting command of the server

**Comment by Bronerman** [comment] 2021-07-16 15:23
There was one recent change that I made.
· Rolls sniping: 0 ($togglesnipe)
· Rolls sniping: 3 ($togglesnipe) => 5 sec.
I've changed that in the txt file to match my $settings

**Comment by vivinano** [comment] 2021-07-16 15:36
ah okay im more concerned about the 
![image](https://user-images.githubusercontent.com/33008397/125972895-5d21490c-9d25-49fd-aecf-34b35ae048b1.png)

making sure that is correct

**Comment by Bronerman** [comment] 2021-07-16 15:39
![Snag_2a77d034](https://user-images.githubusercontent.com/87488178/125973307-343efaf2-da62-4e45-8459-73714cc4ffc8.png)

Yup those settings I haven't changed for awhile

**Comment by vivinano** [comment] 2021-07-16 15:45
![image](https://user-images.githubusercontent.com/33008397/125973535-db8a5645-1640-4d03-aa11-80f9f86afc91.png)

so after line 531 add:
`print(f"roll was in lsat min claim window")`
`print(f"{get_kak(chardes)} kakera found on {charname}")`

this should print as long as something was found during the last min roll cycle and if it doesnt print then it not going within the last min window for some reason. also make sure that a claim was avaible for the bot at the time because if a bot has no claim then everything will be ingored.

**Comment by Bronerman** [comment] 2021-07-16 15:52
Okay I have added those lines to the mudaeautobot.py. 
I should have an available claim coming up in the next 10 minutes so I will see if there is a print out

**Comment by Bronerman** [comment] 2021-07-16 15:58
Oh I was wrong. I'll leave my claims open for the next 3 hour window and let you know.

**Comment by vivinano** [comment] 2021-07-16 16:09
alright let me know i wanna see if it having issues either with determining that it in the window or if its because it not finding kakera value trying to troubleshoot where the fault happens

**Comment by Bronerman** [comment] 2021-07-16 21:33
So I ran two tests so far. At 12:59, (61 mins before reset), I manually rolled a leftover wa command and it did a last minute claim. The printout was correct, but early. 
I turned off the bots and turned them back on at 3:20 (100 mins before reset. 
One bot I manually rolled and claimed.  
![image](https://user-images.githubusercontent.com/87488178/126010398-9b735b4e-210d-4613-b4d7-974714e9b4c0.png)
One bot had an open claim, but no rolls left. 
![Snag_2bb9cd67](https://user-images.githubusercontent.com/87488178/126010438-9c80fdaa-8f0b-4f34-94b9-5ef509a46c0f.png)
One bot had an open claim, and two rolls left. 
![Snag_2bba1f40](https://user-images.githubusercontent.com/87488178/126010458-8d02ded9-7c1f-4ec6-8635-75c0d7127521.png)

As soon as the bot with two rolls left was turned on, the two remaining bots immediately claimed.
I believe the error might be in the window.

**Comment by vivinano** [comment] 2021-07-16 22:03
Is this an issue with claiming or is it an issue with rolling ? Cause it seem like it’s going within the claim window and is making the claim attempt.
Cause im trying to fix one issue which is the last minute claim window the rolling issue can be addressed later

**Comment by Bronerman** [comment] 2021-07-16 22:15
Interestingly, in the last hour before reset at 4:00 PM, this is what I saw. I know there were no claims left open, but there was some odd behaviour.
![image](https://user-images.githubusercontent.com/87488178/126012859-da244482-ed75-43a6-a4f1-57e4e013dd01.png)
 There were 7/16 rolls left and nothing new in the cmd window.
 
![image](https://user-images.githubusercontent.com/87488178/126012957-e59852b6-ca54-48f5-a0b0-93eb2e04b020.png)
There were 2/10 rolls left and nothing new in the cmd window. 

![Snag_2bdcbc84](https://user-images.githubusercontent.com/87488178/126013073-62b7a851-3e06-469b-9657-1d350f193ebf.png)
There were 0/10 rolls left and proper logging of the bots that rolled. 


In response to your question, I think it is an issue with claiming since I had set the last_claim_min as 59 and opened the bots at 100 mins. I believe the bots are claiming early?
And the screenshots above do address there is something odd about the rolling. 

I will leave the bots running for the next 3 hour claim window. My guess is if it is similar to past experiences, is that the bots will either not attempt a last minute claim, or will last min claim at the second try (6:00 PM, reset 8:00 PM with Last_claim_min set as 59. 

I can test to see what will happen.

**Comment by vivinano** [comment] 2021-07-16 22:56
But you keep sending rolling issues and I’m trying to work on issues with the claiming in the last minute >_< we can work on roll issue next but currently want to focus on if or if not you are claiming correctly during the last period

**Comment by Bronerman** [comment] 2021-07-16 23:05
Oh sorry about that! Hmm in the previous example, there should be nothing incorrect with the rolling. I just mostly wanted to test the last_claim_min window as I feel that it is claiming too soon or too late depending on the chosen variable. 

Is my thinking wrong in that if I want the last min claim window to be in the last hour before reset (final roll chance), then the bots should not be doing a last claim min before 59 mins? Since I started the bots up approximately 100 minutes before reset, I was not expecting the bots to try and do a last min claim. 

In an unrelated issue, two of the bots froze (no activity) and I will restart

**Comment by vivinano** [comment] 2021-07-17 00:17
Alright so last min claim is that if you still have a claim it will expand the sniping criteria 

So let’s say you get a normal claim Ex: I rolled a wish character and I claimed it then no claim will be made and all will be ignored until next claim cycle 

Normal claims are priorities so it will and if you still have a claim then it goes into last hour then basically it adds an extra param to snipe so now your able to claim based on min kakera so then it will snipe a character only if it’s within the time frame but 59 mins mean that for 1 min into the new time frame if nothing is rolled nothing would be found because it’s down to the exact seconds of accuracy

**Comment by Bronerman** [comment] 2021-07-17 00:53
I think I understand your logic. Normal claims are priority (series list, name list, min kak). Assuming that no normal claim has been made, then if last_true: true, then it will now snipe claim based on a new min last kak level within the set time frame. 

Based on those new lines of code you gave me, it looks like new min last kak is working properly. I still think there might be an issue with the last claim min window if I'm understanding it correctly. I will get more examples to post. 
Would this make more sense. Let's say claim window is (5-8). If the bot has made no normal claims and if I designate the time frame (last claim min) to be 60 mins, 10 min kak, then at 7, the bot should be within the last true claim window and claim the first roll. 
If the bot makes no claim or a claim at 6, then that would indicate that there is an error in determining the claim window, correct?

**Comment by vivinano** [comment] 2021-07-17 01:39
Yes if it makes no claim it either means that the claim window for last minutes claim is wrong or a kakera value cannot be determined

**Comment by Bronerman** [comment] 2021-07-17 01:54
I'll keep track of how the bots behave for awhile with the print out and try to pinpoint where the error is

**Comment by vivinano** [comment] 2021-07-17 01:56
Let’s do normal min kak is 100 and last min kak is 10 if it doesn’t snipe anything in the first 2 hours and then snipes something during the last cycle then it working as intended

**Comment by Bronerman** [comment] 2021-07-17 01:57
What do you want the last claim min to be?

**Comment by vivinano** [comment] 2021-07-17 02:05
I can be whatever you want it is 59 then that means I has to be 7:01 and after b4 last min snipes can happen

**Comment by Bronerman** [comment] 2021-07-17 02:11
Sounds good, I'll leave it as 59. I cleared my series list and name list too just in case. 
I'll report back after a few runs. Thanks for the all the help

**Comment by Bronerman** [comment] 2021-07-17 22:25
So after 6 test runs, here are the results I found.
Final Results: 
Example claim window of 2-5PM. 

Most common scenario if leaving bots on 24hrs 
If bots are active for full 3 hour window, then no claims made in first two hours even with min 100k are rolled. However, in the last hour, min 100k is active. Last min claim does not activate. An exception I noticed is that since I had leftover rolls (1 or 2 rolls left over sometimes), if a 100+ is manually rolled in earlier hours, then the bot will claim that. 

Reset in first hour 
2-3 PM rolls, no claims made min 100k. Reset before 3PM. 
3PM rolls, bots will now claim min 100k from 3PM-5PM

Reset in second hour 
2-3PM rolls. Reset after 3PM. 
Last min claim activates and whatever first roll will be claimed.  

Reset in third hour 
Activate bot in final hour. 
4PM+. Appears to min 100k claim. Need another test. But Last min claim does not activate.

**Comment by vivinano** [comment] 2021-07-17 23:12
Okay so last min window is working if you start the bot in the 1st and 2nd hour but in the last hour it isn’t working ?

**Comment by Bronerman** [comment] 2021-07-17 23:36
From my tests, last min window works only when the bot is started between second and third hour. It did not work for me when I started it in the last hour. I'll test all 3 bots at 7 to confirm

**Comment by vivinano** [comment] 2021-07-18 00:18
Leave it on for 2 claim cycles so 6 hours ? And see if it run correctly cause the initial start up might not get the next claim hour correctly and all that

**Comment by Bronerman** [comment] 2021-07-18 19:55
I left the bots on for 6 cycles. 1st & 2nd hour no claims even if min 100+ are rolled. Manual rolls that are 100+ are detected though. 
3rd hour, bots will claim any min 100+ roll. 
Last min window did not appear at all during the 6 cycles.

**Comment by vivinano** [comment] 2021-07-18 20:09
Yes because unless 100+ min kak thing are present it will not try to snipe ? So unless its a possible snipe it will not print

**Comment by Bronerman** [comment] 2021-07-18 21:19
Hmm if I'm understanding min_kak correctly, the bot should snipe a claimable character as long as it reaches the minimum kak value. 
I will say that when I previously had it set at my past values of 200, 250, 300 etc, it seemed to function correctly I believe.

It's just that ever since I've been running these test cycles of min_kak 100, the bots refuse to snipe a claimable character of min 100 or higher kak value in the first two hours even if they are rolled. So example for me,  a claimable character of Bubble girl (101k), Machi Komachine (214k), Tsubasa Hanekawa (303k), Krul Tepes (338k), etc. were all available in the first or second hour and the bots never claimed or noticed these characters in the cmd prompt.

**Comment by vivinano** [comment] 2021-07-19 00:59
Okay so then min_kak isn’t working and it doesn’t have anything to do with last min snipe ?? Cause first hour and second hour go off of min_kak and not last_min_kak

**Comment by Bronerman** [comment] 2021-07-19 03:22
I believe that to be the case. That is what I've noticed since removing name list, series list, and lowering the min kak value to 100. I do not believe I changed anything in the code that would have affected that, but I think it used to work as intended with I had it set at higher values of 250 and 300 since I remember the bot claiming those in any hour. 
But to answer the original problem, after leaving the the bots on for many cycles, I did not see the last min claim window activate or get recognized. The only time was on a restart in between the second and third hour. 
I'm sorry that I seem to be finding some issues that may not help with fixing the original problem of the last min claim/last min kak.

**Comment by vivinano** [comment] 2021-07-19 04:07
Send me the setting.json obscuring the the token ofc just to see how you have it set up and see what is going on ?

**Comment by Bronerman** [comment] 2021-07-19 04:20
{
   "token":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
   "channel_ids":[
      854141739266867212
   ],
   "claim_delay":7,
   "kak_delay":4,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"wa",
   "rolling":"True",
   "pkmrolling":"True",
   "series_list":[
      "Rebirth"
   ],
   "namelist":[
      "Li"
   ],
   "emoji_list":[
      "kakera",
      "kakeraT",
      "kakeraG",
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":100,
   "Last_True":"True",
   "last_claim_min":59,
   "min_kak_last_min":10
}

**Comment by Bronerman** [comment] 2021-07-19 04:21
![Snag_377e811c](https://user-images.githubusercontent.com/87488178/126102374-f2f0d34d-3162-47fe-a650-327b83a84515.png)

**Comment by vivinano** [comment] 2021-07-19 04:32
No it’s fine with min kak the calculation is like estimation value so it might be failing to get the correct value 

Check the get_kak function and run some numbers thru there and see if getting correct value or try printing chardes to see if it actually providing values to parse

**Comment by vivinano** [comment] 2021-07-19 05:53
so alright if u ran 1 bot does this issue persist or is it only because 3 bots are running at the same time ?

**Comment by vivinano** [comment] 2021-07-19 06:31
also try 60 for last_claim_min as unless ur rolls happen after 7:01 its not gonna claim

**Comment by vivinano** [comment] 2021-07-19 15:38
![image](https://user-images.githubusercontent.com/33008397/126187214-6cb033ec-ebff-4a8b-a0f3-6625b0200a5b.png)

so far running it overnight im getting correct last minute claims

**Comment by vivinano** [comment] 2021-07-19 16:41
![image](https://user-images.githubusercontent.com/33008397/126196037-28965e0b-b871-4a8f-8902-7a5b18c9661e.png)

**Comment by Bronerman** [comment] 2021-07-20 01:27
So I did test it with 1 bot vs 3 bots and it does seem like that is the reason for why the min kak claim isn't going through in the first two hours. It does work properly with 1 bot, but does not when running 3. 

I did not get last min claim to work yet, but based on your example, I'll try it with those settings. 
I guess there is something different when running 1 vs multiple bots

**Comment by vivinano** [comment] 2021-07-20 01:31
okay so when running 3 bots is there anyone else playing or is this just a bot server and your running 3 bots ? this couild be related to all of them rolling at the same time and Mudae bot itself not being able to respond fast enough

**Comment by Bronerman** [comment] 2021-07-20 01:58
It's just a bot server that I'm playing on. Yeah I guess that would explain why 1 bot functions properly vs 3. So generally, all 3 bots all roll at the exact time which is probably the cause of the problems

**Comment by vivinano** [comment] 2021-07-20 04:45
yeah so on the waifu_roll function u can add a random extra wait so that way all bots roll at a random time

**Comment by vivinano** [comment] 2021-07-20 23:49
![image](https://user-images.githubusercontent.com/33008397/126409039-f4b48241-8d05-48be-8acc-da21933ce2d7.png)

u can add some code to the sleep here which should shutter the bots

**Comment by Bronerman** [comment] 2021-07-21 19:55
Thanks a lot for showing me where to shutter the bots. 
Reading up on the time sleep() method, could I just change the +1 to different integers to randomize the wait

**Comment by vivinano** [comment] 2021-07-23 04:51
u can do a 
`import random` and there should be some functions there that give u back a random number each time 

what i think would work is lets say a .txt with just a bunch of random wait times and then whenever one wait time is selected it edits the .txt file and then after the roll has been finished add the wait variable back into the list so that way you kind of have an idea of when each bot rolls

**Comment by Bronerman** [comment] 2021-07-25 18:45
Oh that's pretty ingenious. Thanks for the guidance. I'll play around and try and get the random implementation to work.

**Comment by vivinano** [comment] 2021-07-25 19:18
Simple random implementation is pretty simple but doing what I mentioned might be a little more complex but I think it something I could work for on in the future

**Comment by Bronerman** [comment] 2021-07-26 13:20
That sounds like a tough project but probably useful for other games. I have learned quite a bit of python from going over your code

**Comment by vivinano** [comment] 2021-07-27 01:32
I’m glad that you are learning python from my code , I would like to state I’m not the greatest dev when it comes to making applications so I’m glad it’s understandable enough that you can easily decipher it. I think it is in part that I’ve tried to limit my use of libraries to just discum and the standard library

**Comment by Bronerman** [comment] 2021-07-28 00:17
I do appreciate that it's from the standard library as it's easy to read up on the function. The code is logical which makes it easy to follow. I haven't gotten my head around discum yet, but I do appreciate the issue creation faqs. I managed to correct my json and update the discum on my own with those links so everything works pretty optimally.

**Comment by vivinano** [comment] 2021-07-28 01:52
The only using standard was more of a self-imposed limitations that I wanted to create something with only things available upon install it turned out for the best tho since installing discum for others has been a headache to explain to others

And the faqs are more of I was exhausted from answering the same questions

**Comment by Bronerman** [comment] 2021-07-30 22:35
Yeah I can see the issues with discum as it's not always intuitive with updating. It's definitely helpful for the coding, but I did see a lot of the same questions/errors being asked. Compared to the other mudae projects that I searched for, I think yours is the simplest while still being supported

**Comment by vivinano** [comment] 2021-08-02 21:26
well the project was originally in discord.py but they have dropped support for selfbots so it was either discum , discord.py (Selfbot branch) or making my own implementation so those being the options I choose discum 

Basically the code originally was written for discord.py when the support for selfbots dropped I was gonna stop the project there but many users requested their desire for the bot to come back so I had to basically re-write the code from nothing as everything was not compatible with the new library.

**Closed by vivinano** 2021-08-02 21:26 UTC
