### ISSUE TITLE
Bot rolls too early

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#39] opened 2021-05-29 09:00 UTC
Bot will roll a minute before roll reset and then won't roll

**Comment by RecentYogurt** [comment] 2021-05-29 09:04
I'd also like to suggest a feature where it rolls randomly between 1 and 5 minutes after the roll reset to mimic human behavior

**Comment by vivinano** [comment] 2021-05-29 12:48
that is strange does it get a wait timer or times out ? cause
logically if it rolls a minute b4 then mudae should give the bot a wait timer of 1 min and then it will wait another minute and roll again ? can you send an image of this issue happening with the wait timer that it print in the console

**Comment by RecentYogurt** [comment] 2021-05-29 18:36
It happened on the latest version, but I'll see if I can get it to do that again. I'm not sure what caused it

**Comment by vivinano** [comment] 2021-05-29 21:28
basically whenever it rolls early since its dynamically obtained if it rolls at

6:14 and roll reset is at 6:15 

mudae should reply with 

Username. the roulette is limited to X uses per hour (high traffic hour). 1 min left.

and then on the console it should print `Waifu Roll:60` and wait for 60

**Comment by vivinano** [comment] 2021-05-31 10:07
Haven't Received any other comment on this issue closing for now until issue can be reproduced

**Closed by vivinano** 2021-05-31 10:07 UTC
