### ISSUE TITLE
Unable to get a list of guilds you are in

### ISSUE THREAD

**Issue by VineST** [vivinano/MudaeAutoBot#266] opened 2023-10-30 18:19 UTC
All the dependencies for the bot appear to be in place, but it looks like Discum's API for getting guilds is broken. Is this true or am I missing something obvious? Can I somehow dump them manually as suggested by your script? Here's the relevant settings and error in question:
![image](https://github.com/vivinano/MudaeAutoBot/assets/6686964/0391197e-ff40-49eb-bf0d-a97f027327d5)

**Comment by vivinano** [comment] 2023-10-31 01:59
Yeah so I think there a separate piece of code I put in as a side script that will just output guilds into a text file Sent from my iPhoneOn Oct 30, 2023, at 2:19 PM, VineST ***@***.***> wrote:﻿
All the dependencies for the bot appear to be in place, but it looks like Discum's API for getting guilds is broken. Is this true or am I missing something obvious? Can I somehow dump them manually as suggested by your script? Here's the relevant settings and error in question:

**Comment by VineST** [comment] 2023-10-31 07:33
Great; where can I find that? Doesn't seem to be in this repo, unless it's buried in the main mudaeautobot.py somewhere. I see two example text files with guild and user config but no way to succinctly fill them with my appropriate data

**Comment by vivinano** [comment] 2024-03-23 13:42
I think this is caused by a limitation of the library im using when the amount of server one joins becomes just really large. I havent tested it yet but as the the script is just there not in the main script

**Comment by Nixeld** [comment] 2024-05-20 09:25
> I think this is caused by a limitation of the library im using when the amount of server one joins becomes just really large. I havent tested it yet but as the the script is just there not in the main script

From what I recall, the problem stems from some text channels having certain characters in the channel topic that causes the variable to be invalid. Can't remember what characters was causing it but I think it was mentioned in 1 of Discum's issues.
![image](https://github.com/vivinano/MudaeAutoBot/assets/18643932/09801756-2456-4a21-bae5-31a16fe58701)

**Comment by Nixeld** [comment] 2024-06-27 19:20
Fixed in https://github.com/Nixeld/Discord-S.C.U.M/commit/eaa07d0c30ea7aac1d2427f4fb6f26d8dcef2069

**Comment by vivinano** [comment] 2024-06-28 00:17
> Fixed in https://github.com/Nixeld/Discord-S.C.U.M/commit/eaa07d0c30ea7aac1d2427f4fb6f26d8dcef2069

Oh nice I can now worry about the simpler things now

**Closed** 2024-09-15 19:32 UTC
